version: '3.9'

services:
  
  backend:
    build: 
      context: .
      dockerfile: docker-compose/backend/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: docker-compose/frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    